version: '3.8'
services:
  go:
    build: ./go
    ports:
      - "8081:8080"
  python:
    build: ./python
    ports:
      - "8082:8080"
  bench:
    build: ./bench
    depends_on:
      - go
      - python
    volumes:
      - ./results:/results
    command: ["/benchmark.sh"]
